### PR TITLE
Blog post for creating an unprivileged k8s account

### PR DESCRIPTION
**Pull request by datho7561**
Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
@vrubezhny this is the write up on setting up a `kind` cluster with restricted permissions. let me know if these steps work for you.

**Comment by datho7561** [comment]
I updated the docs so that the service account that's created in the walkthrough is allowed to view details about individual pods and watch for changes in pods as well.

**Review by vrubezhny — APPROVED** [review]
Looks good to me. 

Used a Kind cluster "restricted" service account to test https://github.com/redhat-developer/vscode-openshift-tools/pull/4122 - all works as expected.

Probably it worth mentioning the limited lifetime of the issued token (can be changed by using `--duration=10h`-like argument) .

Thanks!

**Review by vrubezhny — APPROVED** [review]

**Comment by datho7561** [comment]
I added the `--duration` flag to the token creation step, and updated the publish date to today

**Pull request merged**
